services:
  remix-app:
    container_name: remix-oauth-google
    build: .
    ports:
      - "91:3000"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "bun install && bun run build && bun run start"
    environment:
      NODE_ENV: production
